### ISSUE TITLE
Selecting ensemble algorithm for build_loss_objective

### ISSUE THREAD

**Issue by atrophiedbrain** [SciML/DiffEqParamEstim.jl#129]
When following the monte carlo parameter estimation example (https://docs.juliadiffeq.org/stable/analysis/parameter_estimation/index.html) a deprecation message is received
`parallel_type has been deprecated. Please refer to the docs for the new dispatch-based system.`

When modifying the code to use the new dispatch system as the deprecation message suggests,
```
ensemble_prob = EnsembleProblem(prob)
obj = build_loss_objective(monte_prob,SOSRI(),EnsembleThreads(),L2Loss(t,aggregate_data),
                                     maxiters=10000,verbose=false,trajectories= 1000)
```
The following error results: `MethodError: objects of type EnsembleThreads are not callable`

Chris asked me to create this issue with the message: `open an issue about selecting an ensemble alg, I may need to take a look at that.`

**Comment by ChrisRackauckas** [comment]
Fixed.
