### ISSUE TITLE
Parameter estimation with one data point

### ISSUE THREAD

**Issue by moesphere** [SciML/DiffEqParamEstim.jl#149]
It seems that parameter estimation with one data point does not work as the corresponding loop through the solution starts at index = 2: [here](https://github.com/SciML/DiffEqParamEstim.jl/blob/master/src/cost_functions.jl#L86)

Partially related to this [issue](https://github.com/SciML/DiffEqParamEstim.jl/issues/140)

```julia
using DiffEqParamEstim, DifferentialEquations
function f(du, u, p, t)
    du[1] = dx = p[1] * u[1] - u[1] * u[2]
    du[2] = dy = -3 * u[2] + u[1] * u[2]
end
  
u0 = [1.0; 1.0]
tspan = (0.0, 10.0)
p = [1.5]
prob = ODEProblem(f, u0, tspan, p)
loss_objective = build_loss_objective(prob, Tsit5(), L2Loss([1.], ones(2)))
loss_objective(p) # returns zero
sum((solve(prob)(1.0)-ones(2)).^2) # should return this instead
```

**Comment by CedricLhoussaine** [comment]
I confirm this issue: the parameter estimation always skip the first data point.

**Comment by ChrisRackauckas** [comment]
oh interesting, it would be good to just change that to one. If the initial condition matches, then it's just zero so it won't change that case.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqParamEstim.jl/pull/157
