### ISSUE TITLE
Wrong LogLikeLoss function ?

### ISSUE THREAD

**Issue by CedricLhoussaine** [SciML/DiffEqParamEstim.jl#156]
It seems that the `LogLikeLoss` function (defined line 162 in `cost_functions.jl`) always computes the loglikelihood of the first variable while ignoring the other variables. This means that it fails to estimate the second parameter of this model:
```
f2 = function (du,u,p,t)
  du[1] = p[1] * u[1]
  du[2] = p[2]
end
```
where both variables (and parameters) are independent. I my opinion the reason is this iteration (at least for `UnivariateDistribution`):
https://github.com/SciML/DiffEqParamEstim.jl/blob/ea38ca61e007d0b602d1e2c15c27f24687aade5c/src/cost_functions.jl#L173
where `1:length(sol[1][1])` is always equal to `1:1`. It should instead be `1:length(sol[1])`.

I also wonder if the `MultivariateDistribution` case:
https://github.com/SciML/DiffEqParamEstim.jl/blob/ea38ca61e007d0b602d1e2c15c27f24687aade5c/src/cost_functions.jl#L179-L185
is correct, because of the same problem but also because there's no occurrence of `j` in the body of the loop.

**Comment by ChrisRackauckas** [comment]
>where 1:length(sol[1][1]) is always equal to 1:1. It should instead be 1:length(sol[1]).

Yes, that looks like a bug.
