### ISSUE TITLE
Specify variable to calculate loss on

### ISSUE THREAD

**Issue by aelmokadem** [SciML/DiffEqParamEstim.jl#160]
Hi,

Is there a way that I can define the variable I want to calculate the loss function at using L2Loss? Say I have an ODE with 2 variables and only have observed data for the first one that I want to minimize on, how do I do that? I can't see where in this cost function definition I can do that

```cost_function = build_loss_objective(prob,Tsit5(),L2Loss(t,data), maxiters=10000,verbose=false)```

Thanks.

**Comment by ChrisRackauckas** [comment]
You can just use `save_idxs` for that.

**Comment by aelmokadem** [comment]
@ChrisRackauckas  worked beautifully :)

Thanks.
