### ISSUE TITLE
Update docs: "Using JuMP with DiffEqParamEstim"

### ISSUE THREAD

**Issue by fleimgruber** [SciML/DiffEqParamEstim.jl#187]
In https://github.com/SciML/DiffEqParamEstim.jl/blob/da13a16b350679668cd8bb050990a95f8cb2abc9/docs/src/tutorials/jump.md the JuMP API should be updated for newer JuMP versions. I was not able to make the example work using JuMP 1.1.1 - e.g. the `setsolver` function is not defined.

I tried to adapt the example and came up with these changes (one snippet to experiment better than in the Markdown file). Notable changes: uses `set_optimizer_attribute` instead of `setsolver` and `all_variables` instead of `.colNames`. The problem remains that the variables `σ, ρ, β` remain at their start values, i.e. are not changed in the optimization. Am I missing something?

```julia
using OrdinaryDiffEq, DiffEqParamEstim, JuMP, NLopt, Plots

function g(du,u,p,t)
  σ,ρ,β = p
  x,y,z = u
  du[1] = dx = σ*(y-x)
  du[2] = dy = x*(ρ-z) - y
  du[3] = dz = x*y - β*z
end

u0 = [1.0;0.0;0.0]
t = 0.0:0.01:1.0
tspan = (0.0,1.0)
model_ode(p_) = ODEProblem(g, u0, tspan,p_)
solve_model(mp_) = OrdinaryDiffEq.solve(model_ode(mp_), Tsit5(),saveat=0.01)
mock_data = Array(solve_model([10.0,28.0,8/3]))

loss_objective(mp_, dat) = build_loss_objective(model_ode(mp_), Tsit5(), L2Loss(t,dat))

juobj(args...) = loss_objective(args, mock_data)(args)
jumodel = Model(NLopt.Optimizer)
set_optimizer_attribute(jumodel, "algorithm", :LD_MMA)
JuMP.register(jumodel, :juobj, 3, juobj, autodiff=true)
@variables jumodel begin
    σ,(start=8)
    ρ,(start=25.0)
    β,(start=10/3)
end
@NLobjective(jumodel, Min, juobj(σ, ρ, β))

JuMP.optimize!(jumodel)
best_mp = value.([jumodel[s] for s in Symbol.(all_variables(jumodel))])

sol = OrdinaryDiffEq.solve(best_mp |> model_ode, Tsit5())
plot(getindex.(sol.(t),1))
scatter!(mock_data[1, :], markersize=2)
```

**Comment by ChrisRackauckas** [comment]
Yes it's probably for a much older version of JuMP. It would be good to get some help updating that, and setting it to an `@example` so it gets tested by CI.

**Comment by ChrisRackauckas** [comment]
Or, what's more likely is an update to this library which simply outputs OptimizationProblems. That would probably be the sanest way to do this.

**Comment by fleimgruber** [comment]
Thanks for your thoughts and suggestions!

> Yes it's probably for a much older version of JuMP. It would be good to get some help updating that, and setting it to an @example so it gets tested by CI.

I feel like I could tackle this as I figured out the API changes already - the one missing bit is the unexpected optimization result: the variables still have their start values - but let's look at it in the corresponding PR.

> Or, what's more likely is an update to this library which simply outputs OptimizationProblems. That would probably be the sanest way to do this.

In this case I think a dev should come up with that DiffEqParamEstim API change. In the meantime, changing the docs to `@example` for now would still be good and could be adapted to the new DiffEqParamEstim API later. Also, just curious: is there an actual type you referred to by `OptimizationProblems` or just a generic term for such types?

**Comment by Vaibhavdixit02** [comment]
>Also, just curious: is there an actual type you referred to by "OptimizationProblems" or just a generic term for such types

It's from the Optimization.jl interface

**Comment by ChrisRackauckas** [comment]
This tutorial is now going away due to the revamp to the Optimization.jl interface. The "similar" piece is to use OptimziationMOI.

**Comment by fleimgruber** [comment]
@ChrisRackauckas Thanks for the update and your efforts! I could try my hands at an equivalent tutorial using the new interface if needed. Looking at the tests:

- https://github.com/SciML/DiffEqParamEstim.jl/blob/f27fb46e45f097c8a21b51ed1db2b9b3da2b1fe6/test/lorenz_test.jl
- https://github.com/SciML/DiffEqParamEstim.jl/blob/f27fb46e45f097c8a21b51ed1db2b9b3da2b1fe6/test/lorenz_true_test.jl

which one should go into a tutorial if any?

**Comment by ChrisRackauckas** [comment]
The lorenz_test is a fine one, though I'd say writing it from LV is better because Lorenz is weird and chaotic. If you do Lorenz, it should be done with multiple shooting.

**Comment by ChrisRackauckas** [comment]
The JuMP docs were removed because it's all Optimization.jl now. But we should probably revive something around nonlinear constraints.
