### ISSUE TITLE
CI not running

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqParamEstim.jl#225]
CI is not running properly in this repo, e.g. no CompatHelper, even though workflow file is present.
You can see this because there was no automatic Documenter 1.0 upgrade PR.

**Comment by ChrisRackauckas** [comment]
I just re-enabled the compathelper workflow. Just need to go to Actions/CompatHelper and there's a bar on the top if it hasn't been run in a long time required to re-enable.
